-- Execute no Supabase: SQL Editor → New query → Run
-- Ajustes em relação ao MER textual:
--   * Colunas sem espaços (PostgreSQL: data_criacao, descricao_tarefa).
--   * tarefas.pessoa_id referencia pessoa(id) — várias tarefas por pessoa.
--   * pessoa.auth_user_id liga ao login (Supabase Auth) para a API Flask filtrar por usuário.

create table if not exists public.pessoa (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  cpf character varying not null default '000.000.000-00',
  nome character varying not null default 'CADASTRE UM NOME',
  status character varying not null default 'ATIVA',
  nascimento date null default '1900-01-01',
  auth_user_id uuid null unique references auth.users (id) on delete cascade
);

create table if not exists public.tarefas (
  id bigint generated by default as identity primary key,
  pessoa_id bigint not null references public.pessoa (id) on update cascade on delete cascade,
  data_criacao timestamp with time zone not null default now(),
  data_expiracao date not null,
  descricao_tarefa character varying not null,
  status character varying not null,
  observacao text null default ''::text
);

create index if not exists tarefas_pessoa_id_idx on public.tarefas (pessoa_id);

-- Se a tabela já existia sem este campo, rode no SQL Editor:
-- alter table public.tarefas add column if not exists observacao text null default '';
