import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "." },
  ],
  apiSidebar: [
    {
      type: "category",
      label: "Todo List API",
      link: {
        type: "generated-index",
        title: "Todo List API",
        description: "API de gerenciamento de tarefas do projeto Todo List Over Engineering.",
        slug: "/category/todo-api"
      },
      items: require("./docs/api/sidebar.ts")
    }
  ]
};

export default sidebars;